package pojos;
// Generated Jul 13, 2020 5:08:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import utils.PasswordAuthentication;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer idAccount;
     private String hoTen;
     private String username;
     private String password;
     private String email;
     private boolean active;
     private boolean isAdmin;
     private Set thamgiahoinghis = new HashSet(0);
     
     private String status;

    public Account() {
    }

	
    public Account(String hoTen, String username, String password, String email, boolean active, boolean isAdmin) {
        this.hoTen = hoTen;
        this.username = username;
        
        PasswordAuthentication pwAuth = new PasswordAuthentication();
        String temp  = pwAuth.hash(password);
        this.password = temp;
        this.email = email;
        this.active = active;
        this.isAdmin = isAdmin;
    }
    
    //constructor for table

    public Account(Integer idAccount, String hoTen, String username, String email, boolean active) {
        this.idAccount = idAccount;
        this.hoTen = hoTen;
        this.username = username;
        this.password = password;
        this.email = email;
        this.active = active;
        
        if(active){
            this.status = "Hoạt động";
        }else{
            this.status = "Chặn";
        }
    }
       
    
    public Account(String hoTen, String username, String password, String email, boolean active, boolean isAdmin, Set thamgiahoinghis) {
       this.hoTen = hoTen;
       this.username = username;
       this.password = password;
       this.email = email;
       this.active = active;
       this.isAdmin = isAdmin;
       this.thamgiahoinghis = thamgiahoinghis;
    }
   
    public Integer getIdAccount() {
        return this.idAccount;
    }
    
    public void setIdAccount(Integer idAccount) {
        this.idAccount = idAccount;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Set getThamgiahoinghis() {
        return this.thamgiahoinghis;
    }
    
    public void setThamgiahoinghis(Set thamgiahoinghis) {
        this.thamgiahoinghis = thamgiahoinghis;
    }

    public String getStatus(){
        return this.status;
    }

}


