package pojos;
// Generated Jul 7, 2020 8:28:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer idAccount;
     private String hoTen;
     private String username;
     private String password;
     private String email;
     private boolean isAdmin;
     private Set hoinghis = new HashSet(0);

    public Account() {
    }

	
    public Account(String hoTen, String username, String password, String email, boolean isAdmin) {
        this.hoTen = hoTen;
        this.username = username;
        this.password = password;
        this.email = email;
        this.isAdmin = isAdmin;
    }
    public Account(String hoTen, String username, String password, String email, boolean isAdmin, Set hoinghis) {
       this.hoTen = hoTen;
       this.username = username;
       this.password = password;
       this.email = email;
       this.isAdmin = isAdmin;
       this.hoinghis = hoinghis;
    }
   
    public Integer getIdAccount() {
        return this.idAccount;
    }
    
    public void setIdAccount(Integer idAccount) {
        this.idAccount = idAccount;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Set getHoinghis() {
        return this.hoinghis;
    }
    
    public void setHoinghis(Set hoinghis) {
        this.hoinghis = hoinghis;
    }




}


