package pojos;
// Generated Jul 13, 2020 5:08:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Diadiem generated by hbm2java
 */
public class Diadiem  implements java.io.Serializable {


     private Integer idDiaDiem;
     private String tenDiaDiem;
     private String diaChi;
     private int sucChua;
     private boolean active;
     private Set hoinghis = new HashSet(0);

    public Diadiem() {
    }

	
    public Diadiem(String tenDiaDiem, String diaChi, int sucChua, boolean active) {
        this.tenDiaDiem = tenDiaDiem;
        this.diaChi = diaChi;
        this.sucChua = sucChua;
        this.active = active;
    }
    public Diadiem(String tenDiaDiem, String diaChi, int sucChua, boolean active, Set hoinghis) {
       this.tenDiaDiem = tenDiaDiem;
       this.diaChi = diaChi;
       this.sucChua = sucChua;
       this.active = active;
       this.hoinghis = hoinghis;
    }
   
    public Integer getIdDiaDiem() {
        return this.idDiaDiem;
    }
    
    public void setIdDiaDiem(Integer idDiaDiem) {
        this.idDiaDiem = idDiaDiem;
    }
    public String getTenDiaDiem() {
        return this.tenDiaDiem;
    }
    
    public void setTenDiaDiem(String tenDiaDiem) {
        this.tenDiaDiem = tenDiaDiem;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public int getSucChua() {
        return this.sucChua;
    }
    
    public void setSucChua(int sucChua) {
        this.sucChua = sucChua;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set getHoinghis() {
        return this.hoinghis;
    }
    
    public void setHoinghis(Set hoinghis) {
        this.hoinghis = hoinghis;
    }




}


