package pojos;
// Generated Jul 7, 2020 8:28:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hoinghi generated by hbm2java
 */
public class Hoinghi  implements java.io.Serializable {


     private Integer idHoiNghi;
     private Diadiem diadiem;
     private String tenHoiNghi;
     private String moTaNgan;
     private String moTaChiTiet;
     private byte[] hinhAnh;
     private Date thoiGian;
     private int nguoiThamDu;
     private Set accounts = new HashSet(0);

    public Hoinghi() {
    }

	
    public Hoinghi(Diadiem diadiem, String tenHoiNghi, Date thoiGian, int nguoiThamDu) {
        this.diadiem = diadiem;
        this.tenHoiNghi = tenHoiNghi;
        this.thoiGian = thoiGian;
        this.nguoiThamDu = nguoiThamDu;
    }
    public Hoinghi(Diadiem diadiem, String tenHoiNghi, String moTaNgan, String moTaChiTiet, byte[] hinhAnh, Date thoiGian, int nguoiThamDu, Set accounts) {
       this.diadiem = diadiem;
       this.tenHoiNghi = tenHoiNghi;
       this.moTaNgan = moTaNgan;
       this.moTaChiTiet = moTaChiTiet;
       this.hinhAnh = hinhAnh;
       this.thoiGian = thoiGian;
       this.nguoiThamDu = nguoiThamDu;
       this.accounts = accounts;
    }
   
    public Integer getIdHoiNghi() {
        return this.idHoiNghi;
    }
    
    public void setIdHoiNghi(Integer idHoiNghi) {
        this.idHoiNghi = idHoiNghi;
    }
    public Diadiem getDiadiem() {
        return this.diadiem;
    }
    
    public void setDiadiem(Diadiem diadiem) {
        this.diadiem = diadiem;
    }
    public String getTenHoiNghi() {
        return this.tenHoiNghi;
    }
    
    public void setTenHoiNghi(String tenHoiNghi) {
        this.tenHoiNghi = tenHoiNghi;
    }
    public String getMoTaNgan() {
        return this.moTaNgan;
    }
    
    public void setMoTaNgan(String moTaNgan) {
        this.moTaNgan = moTaNgan;
    }
    public String getMoTaChiTiet() {
        return this.moTaChiTiet;
    }
    
    public void setMoTaChiTiet(String moTaChiTiet) {
        this.moTaChiTiet = moTaChiTiet;
    }
    public byte[] getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(byte[] hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Date getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }
    public int getNguoiThamDu() {
        return this.nguoiThamDu;
    }
    
    public void setNguoiThamDu(int nguoiThamDu) {
        this.nguoiThamDu = nguoiThamDu;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }




}


