package pojos;
// Generated Jul 13, 2020 5:08:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hoinghi generated by hbm2java
 */
public class Hoinghi  implements java.io.Serializable {


     private Integer idHoiNghi;
     private Diadiem diadiem;
     private String tenHoiNghi;
     private String moTaNgan;
     private String moTaChiTiet;
     private byte[] hinhAnh;
     private Date thoiGian;
     private int nguoiThamDu;
     private boolean active;
     private Set thamgiahoinghis = new HashSet(0);

    public Hoinghi() {
    }

	
    public Hoinghi(Diadiem diadiem, String tenHoiNghi, Date thoiGian, int nguoiThamDu, boolean active) {
        this.diadiem = diadiem;
        this.tenHoiNghi = tenHoiNghi;
        this.thoiGian = thoiGian;
        this.nguoiThamDu = nguoiThamDu;
        this.active = active;
    }
    public Hoinghi(Diadiem diadiem, String tenHoiNghi, String moTaNgan, String moTaChiTiet, byte[] hinhAnh, Date thoiGian, int nguoiThamDu, boolean active, Set thamgiahoinghis) {
       this.diadiem = diadiem;
       this.tenHoiNghi = tenHoiNghi;
       this.moTaNgan = moTaNgan;
       this.moTaChiTiet = moTaChiTiet;
       this.hinhAnh = hinhAnh;
       this.thoiGian = thoiGian;
       this.nguoiThamDu = nguoiThamDu;
       this.active = active;
       this.thamgiahoinghis = thamgiahoinghis;
    }
   
    public Integer getIdHoiNghi() {
        return this.idHoiNghi;
    }
    
    public void setIdHoiNghi(Integer idHoiNghi) {
        this.idHoiNghi = idHoiNghi;
    }
    public Diadiem getDiadiem() {
        return this.diadiem;
    }
    
    public void setDiadiem(Diadiem diadiem) {
        this.diadiem = diadiem;
    }
    public String getTenHoiNghi() {
        return this.tenHoiNghi;
    }
    
    public void setTenHoiNghi(String tenHoiNghi) {
        this.tenHoiNghi = tenHoiNghi;
    }
    public String getMoTaNgan() {
        return this.moTaNgan;
    }
    
    public void setMoTaNgan(String moTaNgan) {
        this.moTaNgan = moTaNgan;
    }
    public String getMoTaChiTiet() {
        return this.moTaChiTiet;
    }
    
    public void setMoTaChiTiet(String moTaChiTiet) {
        this.moTaChiTiet = moTaChiTiet;
    }
    public byte[] getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(byte[] hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Date getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }
    public int getNguoiThamDu() {
        return this.nguoiThamDu;
    }
    
    public void setNguoiThamDu(int nguoiThamDu) {
        this.nguoiThamDu = nguoiThamDu;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set getThamgiahoinghis() {
        return this.thamgiahoinghis;
    }
    
    public void setThamgiahoinghis(Set thamgiahoinghis) {
        this.thamgiahoinghis = thamgiahoinghis;
    }




}


